language: node_js

node_js:
  - "6"

services:
  - docker

install:
    - npm install -g bower

script:
    - bower install --force-latest

after_success:
  - rm -rf vendor
  - BRANCH=$TRAVIS_BRANCH COMMIT=${TRAVIS_COMMIT::8} bin/build-docker-image

notifications:
  email:
    - payumsupport@forma-pro.com
